### ISSUE TITLE
Data source

### ISSUE THREAD

**Issue by henadzit** [craft-machine/stock_markets#7]
Hi,

Awesome gem! Could you please comment on where the data comes from? Also what's "STATUS DATE" in the CSV file?

Thanks!

**Comment by henadzit** [comment]
BTW, it would make sense to mention the source of data in README, I bet some of users would want to know!

**Comment by AlexKlim** [comment]
Hey, thanks! 

yes, totally makes sense. We have discussed it today and will update Readme soon.

**Comment by rbUUbr** [comment]
@henadzit Hi! Thanks a lot <3. I have already updated README for source

**Comment by rbUUbr** [comment]
@henadzit also about status date - it is the latest date of updating data for stock market.

**Comment by henadzit** [comment]
Got it, thanks! Closing the issue.
